name: climate_wellbeing
version: "1.0.0"
config-version: 2

profile: climate_wellbeing

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  climate_wellbeing:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
      +schema: marts

seeds:
  climate_wellbeing:
    +schema: raw
    country_overrides:
      +column_types:
        source_name: varchar
        iso_alpha3: varchar
        canonical_name: varchar

sources:
  climate_wellbeing:
    +loaded_at_field: _loaded_at
